thresholds:
  freq_log_common: -7.0
  freq_log_rare: -11.5
  n_lexicons_common: 2
  long_token_len: 14
  wiki_entries_ambiguous_min: 2
  wiki_page_views_review_min: 150
  wiki_total_edits_review_min: 100
  wiki_entries_unambiguous_max: 1

weights:
  ambiguous:
    freq_common: 1.0
    nlex_common: 1.0
    in_wordfreq: 0.5
    wiki_entries: 1.0
  review:
    wiki_views: 1.0
    wiki_edits: 1.0
  unambiguous:
    freq_rare: 1.0
    nlex_zero: 0.5
    len_long: 1.0
    single_entry: 0.5
